name: 'redmine_spent_time_visualizer'
version: 0.0.1
description: A visualizer showing spent time in a redmine project with a spider chart.
#author: Alexander Johr <alexander.johr@gmail.com>
#homepage: http://alexanderjohr.blogspot.de/

analyzer:
  strong-mode: true

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  js: ^0.6.0
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter